import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useCountdown } from "../utils/useCountdown";

const LAUNCH_EVENTS = [];

const Home: NextPage = () => {
  const [days, hours, minutes, seconds] = useCountdown("2022-09-03T20:17:00Z");

  return (
    <>
      <Head>
        <title>Artemis Countdown</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll bg-slate-900"> <div className="text-6xl font-source-code font-black flex flex-row">
        <div className="text-white flex flex-row">
          <div>T-</div>
          <div className="">{hours}</div>
          <div>:</div>
          <div>{minutes}</div>
          <div>:</div>
          <div>{seconds}</div>
        </div>
        </div>
      </div>
    </>
  );
};

export default Home;
